# Standards: 0.11
---

# 3.4.5 Ensure permissions on /etc/hosts.deny are configured

- name: 3.4.5 - Ensure permissions on /etc/hosts.deny are configured
  file:
    path: "/etc/hosts.deny"
    owner: root
    group: root
    mode: 0644
  when: vt_control_hosts_deny_3_4_3 | bool
  tags:
    - level-1
    - section-3
    - "3.4.5"
    - scored
