# Standards: 0.11
---

# 3.6.2 Ensure default deny firewall policy

- name: 3.6.2 - Ensure default deny firewall policy(DROP INPUT)
  iptables:
    chain: "{{item}}"
    jump: DROP
  become: yes
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT
  when: vt_control_activate_iptables | bool and vt_control_firewall_3_6_2 | bool
  tags:
    - level-1
    - section-3
    - "3.6.2"
    - scored
