# This comes in handy when debugging hardening problems.
# With all exclusions uncommented, it will skip every task in the CIS benchmarks
# If you want a task to run, comment it out.

# Here is an example of how I used it.
# Discovered SSH was broken after doing a full run.
# Ran this playbook with all 1.x and 2.x tasks commented out.
# I could still SSH into the instance.
# Ran again with all 3.x tasks commented out and SSH was broken.
# Spun up a new instance and did the 3.x tasks one at a time.
# After each task, I tried SSH again.
# Doscovered 3.4.3 was breaing SSH.
# Added a vt_control variable to the role defaults to disable that check (see the bottom of the file).
# All level 1 tasks succeeded after that change.
---

- name: test hardening
  hosts: test-monthly
  become: True
  
  vars:
    cis_level_1_exclusions: [
      "1.1.1.1",
      "1.1.1.6",
      "1.1.12",
      "1.1.17",
      "1.1.4",
      "1.2.2",
      "1.4.2",
      "1.5.4",
      "1.6.1.5",
      "1.7.1.4",
      "1.1.1.2",
      "1.1.1.7",
      "1.1.13",
      "1.1.18",
      "1.1.5",
      "1.2.3",
      "1.4.3",
      "1.6.1.1",
      "1.6.1.6",
      "1.7.1.5",
      "1.1.1.3",
      "1.1.1.8",
      "1.1.14",
      "1.1.19",
      "1.1.8",
      "1.3.1",
      "1.5.1",
      "1.6.1.2",
      "1.7.1.1",
      "1.7.1.6",
      "1.1.1.4",
      "1.1.10",
      "1.1.15",
      "1.1.2",
      "1.1.9",
      "1.3.2",
      "1.5.2",
      "1.6.1.3",
      "1.7.1.2",
      "1.8",
      "1.1.1.5",
      "1.1.11",
      "1.1.16",
      "1.1.3",
      "1.2.1",
      "1.4.1",
      "1.5.3",
      "1.6.1.4",
      "1.7.1.3",
      "2.1.1",
      "2.1.3",
      "2.1.7",
      "2.2.1.2",
      "2.2.12",
      "2.2.16",
      "2.2.5",
      "2.2.9",
      "2.3.4",
      "2.1.10",
      "2.1.4",
      "2.1.8",
      "2.2.1.3",
      "2.2.13",
      "2.2.2",
      "2.2.6",
      "2.3.1",
      "2.3.5",
      "2.1.11",
      "2.1.5",
      "2.1.9",
      "2.2.10",
      "2.2.14",
      "2.2.3",
      "2.2.7",
      "2.3.2",
      "2.1.2",
      "2.1.6",
      "2.2.1.1",
      "2.2.11",
      "2.2.15",
      "2.2.4",
      "2.2.8",
      "2.3.3",
      "3.1.1",
      "3.2.2",
      "3.2.5",
      "3.2.8",
      "3.3.3",
      "3.4.3",
      "3.5.1",
      "3.5.4",
      "3.6.3",
      "3.1.2",
      "3.2.3",
      "3.2.6",
      "3.3.1",
      "3.4.1",
      "3.4.4",
      "3.5.2",
      "3.6.1",
      "3.6.4",
      "3.2.1",
      "3.2.4",
      "3.2.7",
      "3.3.2",
      "3.4.2",
      "3.4.5",
      "3.5.3",
      "3.6.2",
      "3.6.5",
      "4.2.1.1",
      "4.2.1.3",
      "4.2.1.5",
      "4.2.2.2",
      "4.2.2.4",
      "4.2.3",
      "4.3",
      "4.2.1.2",
      "4.2.1.4",
      "4.2.2.1",
      "4.2.2.3",
      "4.2.2.5",
      "4.2.4",
      "5.1.1",
      "5.1.4",
      "5.1.7",
      "5.2.10",
      "5.2.13",
      "5.2.16",
      "5.2.4",
      "5.2.7",
      "5.3.1",
      "5.3.4",
      "5.4.1.3",
      "5.4.3",
      "5.1.2",
      "5.1.5",
      "5.1.8",
      "5.2.11",
      "5.2.14",
      "5.2.2",
      "5.2.5",
      "5.2.8",
      "5.3.2",
      "5.4.1.1",
      "5.4.1.4",
      "5.4.4",
      "5.1.3",
      "5.1.6",
      "5.2.1",
      "5.2.12",
      "5.2.15",
      "5.2.3",
      "5.2.6",
      "5.2.9",
      "5.3.3",
      "5.4.1.2",
      "5.4.2",
      "5.5",
      #"6.1.1",
      #"6.1.12",
      #"6.1.2",
      #"6.1.5",
      #"6.1.8",
      #"6.2.10",
      #"6.2.13",
      #"6.2.16",
      #"6.2.19",
      #"6.2.4",
      #"6.2.7",
      #"6.1.10",
      #"6.1.13",
      #"6.1.3",
      #"6.1.6",
      #"6.1.9",
      #"6.2.11",
      #"6.2.14",
      #"6.2.17",
      #"6.2.2",
      #"6.2.5",
      #"6.2.8",
      #"6.1.11",
      #"6.1.14",
      #"6.1.4",
      #"6.1.7",
      #"6.2.1",
      #"6.2.12",
      #"6.2.15",
      #"6.2.18",
      #"6.2.3",
      #"6.2.6",
      #"6.2.9"
      ]

  pre_tasks:

    - name: set the cis_sshd_allow_users fact
      set_fact:
        cis_sshd_allow_users: ec2-user

    - name: set the ansible_mounts fact
      set_fact:
        ansible_mounts: []

  roles:
    - ../roles/cis

