---

- name: test hardening
  hosts: test-monthly
  become: True
  
  pre_tasks:

    - name: set the cis_sshd_allow_users fact
      set_fact:
        cis_sshd_allow_users: ec2-user

  roles:
    - ../roles/cis

